export const FETCH_PLANETS = "FETCH_PLANETS";
export const FETCH_PLANETS_SUCCESS = "FETCH_PLANETS_SUCCESS";
export const FETCH_PLANETS_FAILURE = "FETCH_PLANETS_FAILURE";

export const FETCH_VEHICLES = "FETCH_VEHICLES";
export const FETCH_VEHICLES_SUCCESS = "FETCH_VEHICLES_SUCCESS";
export const FETCH_VEHICLES_FAILURE = "FETCH_VEHICLES_FAILURE";

export const SET_VEHICLE_NUM = "SET_VEHICLE_NUM";

export const SELECT_PLANETS = "SELECT_PLANETS";

export const FIND_FALCON = "FIND_FALCON";
